### ISSUE TITLE
One line requires Django 1.9 (final result output) but dependency is Django 1.8

### ISSUE THREAD

**Issue by trevoriancox** [APSL/django-hattori#12]
`style.SUCCESS` was introduced in Django 1.9:
 
`self.stdout.write(self.style.SUCCESS('DONE. Replaced {} values in total'.format(total_replacements_count)))`

resulting in:

`AttributeError: 'Style' object has no attribute 'SUCCESS'`

setup.py documents Django 1.8 dependency

**Comment by mgalofre** [comment]
Fixed!

https://github.com/APSL/django-hattori/releases/tag/0.2.1

Thanks for the report
